### ISSUE TITLE
how to pass a `store` down a nested component hierarchy?

### ISSUE THREAD

**Issue by Kosta-Github** [mweststrate/mobservable-react#14]
What is the best/recommended way to pass a `store` down a nested component hierarchy if I don't want to use a `global` object for that?

Is there something like the `<Provider store={myStore}>` mechanism from `react-redux`. I haven't found anything related to that neither in the docs nor in the test suite...

**Comment by Kosta-Github** [comment]
Answering myself: OK, I'll go with explicitly passing the `store` on from component to component down the nested hierarchy...

**Comment by mweststrate** [comment]
Yeah, I always do that as well. You could (like redux connect) use React's context mechanism, but to me it makes it a bit obscure.
