### ISSUE TITLE
Note that React must be loaded before moservables-react in included

### ISSUE THREAD

**Issue by mattruby** [mweststrate/mobservable-react#2]
Please note that mobservable-react must be included after react.

**Comment by mweststrate** [comment]
Hi Matt, 

Can you describe in which case you did run into this issue? Did you manually include the scripts in your app, or did you use something like browserify or webpack?

**Comment by mattruby** [comment]
I manually added the scripts.  I was getting the weirdest error message
just on react render. Going against the store direct would trigger
correctly.

**Comment by mweststrate** [comment]
Ok, thanks for the info! I'll add it to the notes and will check in the
script as well whether React is available.
