### ISSUE TITLE
React is updating a component multiple times when the observable is modified outside of react.

### ISSUE THREAD

**Issue by mattruby** [mweststrate/mobservable-react#21]
http://jsbin.com/gegagu/5/edit?js,output

In this example, you may click on the steps to activate them.  You'll see that the active step at the top is updating once per transaction change.  When you click the buttons below the steps, you'll see that the active step is updating multiple times.

**Comment by mweststrate** [comment]
Confirmed, the component is rendering twice; one time because the things it has observing is changed, and one time because it got changed props from its parent (`props.step`). Will investigate whether this double invalidation can be optimized away

**Comment by mweststrate** [comment]
Ok implemented a solution for this, which will be part of the next major version of `mobservable-react`.

**Comment by mattruby** [comment]
Thanks!  Looks like an interesting fix.  Looks like it will skip the first render pass if another change is waiting behind it.
