### ISSUE TITLE
debugging aids?

### ISSUE THREAD

**Issue by Kosta-Github** [mweststrate/mobservable-react#22]
Are there some more debugging aids available hidden somewhere inside the code?

I would like to track down, why a `react` component doesn't get updated automatically although it displays an observable value. How would I track down the issue best?

I haven't managed to get a down-stripped version of my issue yet. The following is a small example that is very similar to my case, but this is working as expected:
```JavaScript
import React from 'react';
import mobs  from 'mobservable';
import mobsr from 'mobservable-react';
require("mobservable-react-devtools");

const tree = mobs.observable(
    { name: 'root_name', data: 1, collapsed: false, children: [
        { name: 'child_1', data: 2 },
        { name: 'child_2', data: 3, collapsed: false, children: [
            { name: 'child_2_1', data: 4 }
        ] }
    ] }
);

const TreeComponent = mobsr.observer(({ tree }) => {
    const hasChildren  = tree.children && tree.children.length;
    const openClose    = hasChildren ? <span>{tree.collapsed ? '[OPEN] ' : '[CLOSE] '}</span> : null;
    const showChildren = hasChildren && !tree.collapsed;
    return <div>
        <li><span>{openClose}{tree.name}: {tree.data}</span></li>
        {showChildren && <ul>{tree.children.map((c, idx) => <TreeComponent key={idx} tree={c} />)}</ul>}
    </div>;
});

ReactDOM.render(
    <ul><TreeComponent tree={tree} /></ul>,
    document.getElementById('app_id')
);

setInterval(() => { tree.children[0].data = Math.random(); }, 3000);
setInterval(() => { tree.children[1].name = Math.random(); }, 4500);
setInterval(() => { tree.collapsed = !tree.collapsed; }, 7000);
setInterval(() => { tree.children[1].collapsed = !tree.children[1].collapsed; }, 4000);
```
My case is very similar, except that it doesn't react to changes of `collapsed` automatically. I need to add the following `propTypes` definition to make it actually working:
```JavaScript
TreeComponent.propTypes = {
    tree: React.PropTypes.shape({
        collapsed: React.PropTypes.bool
    })
}
```
The bad thing about that is, it stops working again, when switching to `production` mode, since then `react` ignores the `propTypes` definitions.

How would/could I track down the issue best?

**Comment by mweststrate** [comment]
If you enable the transaction in the devtools log you should be able to see which individual observables are triggered and readied. It's not the most easy to read output but it might help if you study it closely.

Besides that, `mobservable.extras` contains some utilities to print the dependency / observer tree of an observable value. So you could do things in your code like

`console.log(mobservable.extras.getDependencyTree(mycomponent.render))` or `console.log(mobservable.extras.getObserverTree(tree.children[0], 'name'))`

If you have any other suggestions which would improve debugging feel free to suggest them!

----

Besides that, I'm really surprised that (not) setting `propTypes` affects your script. I hardly ever use them (since we do everything in typescript) so they really shouldn't be needed. Are you maybe using other decorators or higher order components that use the propTypes?

**Comment by Kosta-Github** [comment]
Yeah, these `extras` do help.

-------
> Are you maybe using other decorators or higher order components that use the `propTypes`?

Yes, I am using additional `HOCs` (for mapping app `state` to `props` (home grown solution) + `react-intl 2.x`). And these `HOCs` also use the [react `context` mechanism](https://facebook.github.io/react/docs/context.html) for passing data down the hierarchy.

I simplified my home-grown solution doing the `state-to-props` mapping to use a `stateless` rendering wrapper function instead of a full-blown `React.Component` class, which in turn gets wrapped by `mobs.observer()`.

With this PR https://github.com/mweststrate/mobservable-react/pull/23 I got everything working as expected...

**Comment by Kosta-Github** [comment]
Sorry, but I need to reopen it again. My changes didn't solve the issue yet.

I still need to further investigate further this issue. It seems to be related to my `state-to-props` wrapper in between; but adding the `propTypes` to the basic component to be wrapped, solves the issue...

**Comment by Kosta-Github** [comment]
OK, the issue was related to my own wrapping code.

Just for the record: I was using this simplistic wrapping scheme for wrapping a component `Component`:
```JavaScript
    const Component = ...;

    const render = (props, context) => {
        const mergedProps = mapAndMergeProps(props, context);
        return <Component {...mergedProps} />;
    }
    render.displayName = 'AppStateToPropsMapper(' + Component.displayName + ')';
    render.contextTypes = { appState: React.PropTypes.any, ...Component.contextTypes };

    const obsRender = mobsr.observer(render);
    return obsRender;
```
But that doesn't work that well and some of the `observable` values were not tracked correctly/at all with respect to the wrapped `Component`, so I needed to make it a bit more sophisticated and make an explicit differentiation between stateless render functions and full-blown render components like this:
```JavaScript
    const Component = ...;

    const isStatelessRender = (comp) => {
        return (typeof comp === "function" && !comp.prototype.render && !comp.isReactClass && !React.Component.isPrototypeOf(comp));
    }

    let render = Component;
    if (isStatelessRender(Component)) {
        render = (props, context) => {
            const mergedProps = mapAndMergeProps(props, context);
            return Component.call(Component, mergedProps, context);
        }
    } else {
        Component._origRender = Component._origRender || Component.render;
        Component.render = function() {
            this.props = mapAndMergeProps(this.props, this.context);
            return Component._origRender.call(this);
        }
    }
    render.displayName = render.displayName || ('AppStateToPropsMapper(' + Component.displayName + ')');
    render.contextTypes = { appState: React.PropTypes.any, ...Component.contextTypes };

    const obsRender = mobsr.observer(render);
    return obsRender;
```
