### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by mrjjwright** [mweststrate/mobservable-react#3]
Does this lib work with React Native?  If not, any idea what it would take to make it work?

**Comment by mweststrate** [comment]
Hi John,

I didn't verify it myself yet, but several others confirmed that it works
with react native. Which makes sense since it doesn't rely on the DOM, just
on the normal react lifecycle events :).

**Comment by mrjjwright** [comment]
Thanks for the response. Yeah, I got it to work temporarily by simply changing `require("react")` with `require("react-native")` in the index.js for mobservable-react.   Not sure how the others did it.  Also, when a React Native component throws a non observable related error throws an error it shows up  in the red screen of death as a mobservable error obscuring the underlying error.  Of course checking the Chrome console shows it, but it's a tad inconvenient.   This lib is awesome, much thanks!

**Comment by mweststrate** [comment]
Good points, I will improve the dependency checks, to see whether either `react` or `react-native` is available. Version 1.0 (planned for next week) will no longer catch any errors inside render functions, so that should fix the issue of obscured errors.

**Comment by mweststrate** [comment]
I've just published version 0.2.1, which tries to use either React or React-Native (whatever is available). Could you verify that this works as expected?

Thanks!

**Comment by mweststrate** [comment]
Apologies, it should be 0.2.2.

**Comment by mrjjwright** [comment]
That works thanks!

**Comment by mweststrate** [comment]
The current setup gave issues with consumers that used webpack for building, so the proper way to use mobservable-react with react-native is now to require from `mobservable-react/native` instead of just `mobservable-react`.

**Comment by mrjjwright** [comment]
Got it, that makes sense.

On Mon, Oct 12, 2015 at 7:15 AM, Michel Weststrate <notifications@github.com
