### ISSUE TITLE
Convert to simple object

### ISSUE THREAD

**Issue by mrjjwright** [mweststrate/mobservable-react#4]
Hi I am storing an object in an mobservable store that represents a React `style` object so that I can update styles from within my app.  When I update it , e.g. change the `borderColor` and my React component re-renders nothing changes.  If I transfer the `style` props to a regular JS object manually it works.

`const theStyle = {...store.currentStyle}`

Any idea why?

**Comment by mweststrate** [comment]
Hi,

Mobservable doesn't convert non-plain objects automatically, as that is considered to be the responsibility of the (constructor of) the object, as making the object observable could potentially interfere with the inner workings of the object.

However, using `mobservable.extendReactive` you can simply add additional properties to an existing object, like `mobservable.extendReactive(store.currentStyle, { width: 3 })`, or even make all properties of the object observable at once by using `mobservable.extendReactive(store.currentStyle, store.currentStyle)`.

**Comment by mrjjwright** [comment]
Thanks so much, yeah I figured that out after a while.  This all sounds
awesome, so glad I found this library.

On Sun, Oct 11, 2015 at 8:28 AM, Michel Weststrate <notifications@github.com
