### ISSUE TITLE
PropTypes are not checked on the component after calling observer(component) on it

### ISSUE THREAD

**Issue by capaj** [mweststrate/mobservable-react#7]
This sucks badly if you seriously use PropTypes.

I tried this on stateless component, but I think this bug might occur for normal components as well.

**Comment by mweststrate** [comment]
We didn't use propTypes yet as we use typescript which infers the property types at compile time from the definitions. So thanks for this useful contribution! Just published it as version `2.0.1`. 

I will add tests for it (after switching to tape & tape-run, the current jsdom setup is quite unreliable on different node environments), but normal components are not defined on the fly as is done for stateless components, so propTypes should work out of the box for them.
